### ISSUE TITLE
Need help getting a Release version with a tag

### ISSUE THREAD

**Issue by ScottLeWarne** [release-flow/release-flow#19]
@richtea I'm having some trouble figuring out how to create a tag that will be seen as a 'release tag', can you help me figure out what I am doing wrong?

Here is my rfconfig.yml:

![image](https://github.com/release-flow/release-flow/assets/5997637/1224c861-c58d-4e0f-8f69-e5e071e83e65)

I have a release branch named '**release/sprint45**'

I also have a tag on the latest commit of release/sprint45 named '**v45.1**'.
That tag is getting ignored and I'm not sure why.
I'm testing this locally from the command line, no azure pipelines are involved.

The full debug output is attached, but here is a chunk of it where it seems to be seeing the tag along with the other branches, but then says next that it didn't find any release version tags and I get a 'beta' version.

![image](https://github.com/release-flow/release-flow/assets/5997637/e70b610f-716a-4cb2-a892-0f9d3e94a08d)

Does anything stand out?  Any other info I can provide?  
thx
Scott
[release-flow-output.txt](https://github.com/release-flow/release-flow/files/11512579/release-flow-output.txt)

**Comment by richtea** [comment]
Hi Scott, what command-line parameters are you passing? In particular, what value are you passing for `--source-ref`? This needs to be in the form `refs/tags/v45.1` or `refs/heads/tags/v45.1` in order for the library to identify a release build type (see [test 1](https://github.com/release-flow/release-flow/blob/166c031559d8e35b4f2c6ee3cfb336e5bd08533e/src/BuildVersionCalculator.spec.ts#L219) and [test 2](https://github.com/release-flow/release-flow/blob/166c031559d8e35b4f2c6ee3cfb336e5bd08533e/src/BuildVersionCalculator.spec.ts#LL251C53-L251C53)).

**Comment by ScottLeWarne** [comment]
Ah, got it.  I wasn't passing any parameters, other than --pretty, and as it was mostly working I didn't think to go back to the parameters, and I think assumed it would find the tag on it's own.  I've been using GitVersion for a few years and got used to that one.

That leads me to another question then, when using this in an Azure pipeline it sounds like I need to figure out myself whether a build should use a tag and conditionally pass that to the pipeline tasks's 'SourceBranch' input?  It sounds like it won't just find the tag on it's own?

Do you have/know of any example pipelines?  We typically just have a single pipeline that runs for any branch, trying to determine if we'll need to change that approach or not.  I looked through the tests in the extension repo but nothing jumped out.

**Comment by richtea** [comment]
Azure Pipelines provide a handy predefined variable called `$(Build.SourceBranch)` that specifies the branch or tag related to the build trigger (see [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)).

The Release Flow [Azure DevOps extension](https://marketplace.visualstudio.com/items?itemName=release-flow-dev.release-flow-tools) works all this out for you - see its [task.json file](https://github.com/release-flow/azure-pipelines-extension/blob/3f4a3e6e5291db0f04aa0cf3cf451038b6611fe5/tasks/ReleaseFlowGitVersionV0/task.json#LL36C26-L36C44) for how it sets the variable by default. The design principle for the extension is that you shouldn't need to configure very much if anything, as long as you fit into my somewhat opinionated way of doing things :wink:

If you still prefer to use the command line, the extension's build pipeline contains a [step](https://github.com/release-flow/azure-pipelines-extension/blob/3f4a3e6e5291db0f04aa0cf3cf451038b6611fe5/build/azure-pipelines.yml#LL70C1-L78C33) that runs `rfver`. Hopefully that will get you started. That pipeline will work for any branch / tag. In my preferred setup, it runs automatically for commits to `main` and release branches, and also for release tags - see the [trigger](https://github.com/release-flow/azure-pipelines-extension/blob/3f4a3e6e5291db0f04aa0cf3cf451038b6611fe5/build/azure-pipelines.yml#LL12C1-L21C17).

(BTW I'm on vacation for the next couple of weeks, so any future replies might not be prompt - apologies in advance!)

**Comment by ScottLeWarne** [comment]
Awesome, thanks for the pointers.  

Have a great vacation!
